[package]
name = "dwrite-benchmarks"
version = "0.1.0"
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["dwrite"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "dwrite_benchmark"
harness = false